name: Release to production

on:
  release:
    types: [released]

jobs:
  build_linux:
    name: Build
    uses: ./.github/workflows/build_single_preset.yml
    with:
      godot-export-preset: linux
      file-extension: x86_64
      debug-mode: false

  build_mac:
    name: Build
    uses: ./.github/workflows/build_single_preset.yml
    with:
      godot-export-preset: mac
      file-extension: zip
      debug-mode: false

  build_web:
    name: Build
    uses: ./.github/workflows/build_single_preset.yml
    with:
      godot-export-preset: web
      file-extension: html
      export-file-name: index
      debug-mode: false

  build_windows:
    name: Build
    uses: ./.github/workflows/build_single_preset.yml
    with:
      godot-export-preset: windows
      file-extension: exe
      debug-mode: false

  release_linux:
    needs: [build_linux, build_mac, build_web, build_windows]
    name: Release
    uses: ./.github/workflows/release_artifact.yml
    with:
      release-channel: linux-production
      artifact-name: ${{ needs.build_linux.outputs.artifact-name }}
    secrets: inherit

  release_mac:
    needs: [build_linux, build_mac, build_web, build_windows]
    name: Release
    uses: ./.github/workflows/release_artifact.yml
    with:
      release-channel: mac-production
      artifact-name: ${{ needs.build_mac.outputs.artifact-name }}
    secrets: inherit

  release_web:
    needs: [build_linux, build_mac, build_web, build_windows]
    name: Release
    uses: ./.github/workflows/release_artifact.yml
    with:
      release-channel: web-production
      artifact-name: ${{ needs.build_web.outputs.artifact-name }}
    secrets: inherit

  release_windows:
    needs: [build_linux, build_mac, build_web, build_windows]
    name: Release
    uses: ./.github/workflows/release_artifact.yml
    with:
      release-channel: windows-production
      artifact-name: ${{ needs.build_windows.outputs.artifact-name }}
    secrets: inherit

  tag_commit:
    needs: [release_linux, release_mac, release_web, release_windows]

    name: Create tag release-${{ github.run_number }}
    runs-on: ubuntu-latest

    steps:
      - name: Tag commit
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: release-${{ github.run_number }}
          tag_prefix: ""
