name: Release an artifact

on:
  # Used when triggering this workflow from another workflow
  workflow_call:
    inputs:
      release-channel:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  release_to_itch:
    name: ${{ inputs.release-channel }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      id: download-artifact
      name: Download artifact to release
      with:
        name: ${{ inputs.artifact-name }}

    - uses: manleydev/butler-publish-itchio-action@v1.0.3
      name: Upload artifact to Itch.io ${{ inputs.release-channel }} channel
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: ${{ inputs.release-channel }}
        ITCH_GAME: ${{ secrets.ITCH_GAME }}
        ITCH_USER: ${{ secrets.ITCH_USER }}
        PACKAGE: ${{ steps.download-artifact.outputs.download-path }}
        VERSION: ${{ github.ref_name }}
